dist: trusty
language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script: vendor/bin/phpunit test/
